application:
  name: thor
  host: localhost
  port: 8088

log:
  level: info
  dir: ./storage/logs
  filename: app.log
  format: json
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 30
  compress: true

database:
  driver: mysql
  host: 10.37.2.220
  port: 3306
  database: db_drill
  username: root
  password: mysql123
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
  enable_file_log_writer: true
  log_filename: sql.log
redis:
  host: 172.16.1.223
  port: 6379
  db: 0
  password: redis123
jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 43200
rabbitmq:
  addr: 172.16.1.223
  port: 5672
  user: admin
  password: rabbitmq123